### ISSUE TITLE
Tiny CSS tweak on placeholder site.

### ISSUE THREAD

**Issue by chriskrycho** [pillarlabs/ministry.careers#1]
For the dot in ministry dot careers, add the following:

``` css
.that-span {
    margin-left: -0.1em;
    margin-right: -0.05em;
}
```

The result is a slightly tighter look on the logotype.

Do something similar with the right side of the en dash in the years.
